import fs from 'fs';
import path from 'path';

// Authenticated real banks (Regional banks, State banks, Sparkassen, Banques Populaires, Building societies)
const networkBanks = [
  // ==================== UNITED STATES (State & Super-Regional Commercial Banks) ====================
  { bic: 'CINAUS6LXXX', name: 'CITY NATIONAL BANK (RBC USA)', country: 'UNITED STATES', city: 'LOS ANGELES' },
  { bic: 'FHOVUS44XXX', name: 'FIRST HORIZON BANK', country: 'UNITED STATES', city: 'MEMPHIS' },
  { bic: 'SSBCUS44XXX', name: 'SOUTHSTATE BANK, N.A.', country: 'UNITED STATES', city: 'WINTER HAVEN' },
  { bic: 'PNFPUS44XXX', name: 'PINNACLE FINANCIAL PARTNERS (PINNACLE BANK)', country: 'UNITED STATES', city: 'NASHVILLE' },
  { bic: 'UCBIUS44XXX', name: 'UNITED COMMUNITY BANK', country: 'UNITED STATES', city: 'GREENVILLE' },
  { bic: 'ONBKTX44XXX', name: 'OLD NATIONAL BANK', country: 'UNITED STATES', city: 'EVANSVILLE' },
  { bic: 'FNBPA44XXXX', name: 'FIRST NATIONAL BANK OF PENNSYLVANIA (FNB CORP)', country: 'UNITED STATES', city: 'PITTSBURGH' },
  { bic: 'VLYNUS33XXX', name: 'VALLEY NATIONAL BANK', country: 'UNITED STATES', city: 'WAYNE' },
  { bic: 'BOKFUS44XXX', name: 'BOK FINANCIAL, N.A. (BANK OF OKLAHOMA)', country: 'UNITED STATES', city: 'TULSA' },
  { bic: 'GBCIUS55XXX', name: 'GLACIER BANK', country: 'UNITED STATES', city: 'KALISPELL' },
  { bic: 'WFEDUS66XXX', name: 'WASHINGTON FEDERAL BANK (WAFD BANK)', country: 'UNITED STATES', city: 'SEATTLE' },
  { bic: 'BANRUS66XXX', name: 'BANNER BANK', country: 'UNITED STATES', city: 'WALLA WALLA' },
  { bic: 'COLBUS66XXX', name: 'COLUMBIA BANKING SYSTEM (COLUMBIA BANK)', country: 'UNITED STATES', city: 'TACOMA' },
  { bic: 'UMPQUS66XXX', name: 'UMPQUA BANK', country: 'UNITED STATES', city: 'PORTLAND' },
  { bic: 'FIBKUS55XXX', name: 'FIRST INTERSTATE BANK', country: 'UNITED STATES', city: 'BILLINGS' },
  { bic: 'PABWUS66XXX', name: 'PACIFIC WESTERN BANK (BANC OF CALIFORNIA)', country: 'UNITED STATES', city: 'LOS ANGELES' },
  { bic: 'BOCAUS66XXX', name: 'BANC OF CALIFORNIA, N.A.', country: 'UNITED STATES', city: 'SANTA ANA' },
  { bic: 'CATYUS66XXX', name: 'CATHAY BANK', country: 'UNITED STATES', city: 'LOS ANGELES' },
  { bic: 'AXOSUS66XXX', name: 'AXOS BANK', country: 'UNITED STATES', city: 'SAN DIEGO' },
  { bic: 'MBWMI44XXXX', name: 'MERCANTILE BANK', country: 'UNITED STATES', city: 'GRAND RAPIDS' },
  { bic: 'RNSTUS44XXX', name: 'RENASANT BANK', country: 'UNITED STATES', city: 'TUPELO' },
  { bic: 'SIMBUS44XXX', name: 'SIMMONS BANK', country: 'UNITED STATES', city: 'PINE BLUFF' },
  { bic: 'WHITUS44XXX', name: 'HANCOCK WHITNEY BANK', country: 'UNITED STATES', city: 'GULFPORT' },
  { bic: 'CADEUS44XXX', name: 'CADENCE BANK', country: 'UNITED STATES', city: 'TUPELO' },
  { bic: 'ARVEST44XXX', name: 'ARVEST BANK', country: 'UNITED STATES', city: 'FAYETTEVILLE' },
  { bic: 'TRMKUS44XXX', name: 'TRUSTMARK NATIONAL BANK', country: 'UNITED STATES', city: 'JACKSON' },
  { bic: 'HOMBCA44XXX', name: 'CENTENNIAL BANK (HOME BANCSHARES)', country: 'UNITED STATES', city: 'CONWAY' },
  { bic: 'PRSPTX44XXX', name: 'PROSPERITY BANK', country: 'UNITED STATES', city: 'EL CAMPO' },
  { bic: 'TCBITX44XXX', name: 'TEXAS CAPITAL BANK', country: 'UNITED STATES', city: 'DALLAS' },
  { bic: 'INDBUS44XXX', name: 'INDEPENDENT BANK', country: 'UNITED STATES', city: 'MCKINNEY' },
  { bic: 'MDFROK44XXX', name: 'MIDFIRST BANK', country: 'UNITED STATES', city: 'OKLAHOMA CITY' },
  { bic: 'BELLND44XXX', name: 'BELL BANK', country: 'UNITED STATES', city: 'FARGO' },
  { bic: 'FFINOH44XXX', name: 'FIRST FINANCIAL BANK', country: 'UNITED STATES', city: 'CINCINNATI' },
  { bic: 'WSBCWV44XXX', name: 'WESBANCO BANK, INC.', country: 'UNITED STATES', city: 'WHEELING' },
  { bic: 'PARKOH44XXX', name: 'THE PARK NATIONAL BANK', country: 'UNITED STATES', city: 'NEWARK' },
  { bic: 'CBNYUS33XXX', name: 'COMMUNITY BANK SYSTEM (COMMUNITY BANK, N.A.)', country: 'UNITED STATES', city: 'DEWITT' },
  { bic: 'FULTUS33XXX', name: 'FULTON BANK, N.A.', country: 'UNITED STATES', city: 'LANCASTER' },
  { bic: 'PVBIUS33XXX', name: 'PROVIDENT BANK', country: 'UNITED STATES', city: 'ISELIN' },
  { bic: 'OCFCUS33XXX', name: 'OCEANFIRST BANK, N.A.', country: 'UNITED STATES', city: 'RED BANK' },
  { bic: 'WSFSUS33XXX', name: 'WSFS BANK (WILMINGTON SAVINGS FUND SOCIETY)', country: 'UNITED STATES', city: 'WILMINGTON' },
  { bic: 'SASBUS33XXX', name: 'SANDY SPRING BANK', country: 'UNITED STATES', city: 'OLNEY' },
  { bic: 'UBVRUS33XXX', name: 'ATLANTIC UNION BANK', country: 'UNITED STATES', city: 'RICHMOND' },
  { bic: 'TOWNUS33XXX', name: 'TOWNEBANK', country: 'UNITED STATES', city: 'PORTSMOUTH' },
  { bic: 'EBTCUS33XXX', name: 'EASTERN BANK', country: 'UNITED STATES', city: 'BOSTON' },
  { bic: 'CATCUS33XXX', name: 'CAMBRIDGE TRUST COMPANY', country: 'UNITED STATES', city: 'CAMBRIDGE' },
  { bic: 'BHLBUS33XXX', name: 'BERKSHIRE BANK', country: 'UNITED STATES', city: 'BOSTON' },
  { bic: 'WASHUS33XXX', name: 'THE WASHINGTON TRUST COMPANY', country: 'UNITED STATES', city: 'WESTERLY' },
  { bic: 'BHBTUS33XXX', name: 'BAR HARBOR BANK & TRUST', country: 'UNITED STATES', city: 'BAR HARBOR' },
  { bic: 'CACNUS33XXX', name: 'CAMDEN NATIONAL BANK', country: 'UNITED STATES', city: 'CAMDEN' },
  { bic: 'BNGRUS33XXX', name: 'BANGOR SAVINGS BANK', country: 'UNITED STATES', city: 'BANGOR' },
  { bic: 'AMEGUS44XXX', name: 'AMERIS BANK', country: 'UNITED STATES', city: 'ATLANTA' },
  { bic: 'TRSTTX44XXX', name: 'SOUTH TEXAS NATIONAL BANK', country: 'UNITED STATES', city: 'LAREDO' },
  { bic: 'IBCBUS44XXX', name: 'INTERNATIONAL BANCSHARES CORPORATION (IBC BANK)', country: 'UNITED STATES', city: 'LAREDO' },
  { bic: 'SEASUS66XXX', name: 'SEACOAST NATIONAL BANK', country: 'UNITED STATES', city: 'STUART' },
  { bic: 'C1BKUS33XXX', name: 'BANK OZK', country: 'UNITED STATES', city: 'LITTLE ROCK' },
  { bic: 'FCFSPA44XXX', name: 'FIRST COMMONWEALTH BANK', country: 'UNITED STATES', city: 'INDIANA' },
  { bic: 'SIVBUS44XXX', name: 'SILICON VALLEY BRIDGE BANK, N.A.', country: 'UNITED STATES', city: 'SANTA CLARA' },
  { bic: 'SIGNUS33XXX', name: 'SIGNATURE BRIDGE BANK, N.A.', country: 'UNITED STATES', city: 'NEW YORK' },
  { bic: 'FRCUS66XXXX', name: 'FIRST REPUBLIC BANK (JPMORGAN DIVISION)', country: 'UNITED STATES', city: 'SAN FRANCISCO' },
  { bic: 'TRICUS66XXX', name: 'TRI COUNTIES BANK', country: 'UNITED STATES', city: 'CHICO' },
  { bic: 'CVBFUS66XXX', name: 'CITIZENS BUSINESS BANK', country: 'UNITED STATES', city: 'ONTARIO' },
  { bic: 'CVLYUS66XXX', name: 'CENTRAL VALLEY COMMUNITY BANK', country: 'UNITED STATES', city: 'FRESNO' },
  { bic: 'FRMCUS66XXX', name: 'FARMERS & MERCHANTS BANK OF LONG BEACH', country: 'UNITED STATES', city: 'LONG BEACH' },
  { bic: 'HERTUS66XXX', name: 'HERITAGE BANK OF COMMERCE', country: 'UNITED STATES', city: 'SAN JOSE' },
  { bic: 'WAFDUS66XXX', name: 'WESTMINSTER BANK USA', country: 'UNITED STATES', city: 'LOS ANGELES' },
  { bic: 'STCUUS66XXX', name: 'SPOKANE TEACHERS CREDIT UNION (COMMERCIAL DIV)', country: 'UNITED STATES', city: 'SPOKANE' },
  { bic: 'BEACONUS33X', name: 'BEACON FEDERAL CREDIT BANK', country: 'UNITED STATES', city: 'PHILADELPHIA' },
  { bic: 'MIDWUS44XXX', name: 'MIDWEST BANKCENTRE', country: 'UNITED STATES', city: 'ST. LOUIS' },
  { bic: 'FIRSTUS44XXX', name: 'FIRST MID BANK & TRUST', country: 'UNITED STATES', city: 'MATTOON' },
  { bic: 'HEARTUS44XX', name: 'HEARTLAND FINANCIAL USA', country: 'UNITED STATES', city: 'DUBUQUE' },
  { bic: 'QCRHUS44XXX', name: 'QCR HOLDINGS (QUAD CITY BANK & TRUST)', country: 'UNITED STATES', city: 'MOLINE' },
  { bic: 'MIDFUS44XXX', name: 'MIDLAND STATES BANK', country: 'UNITED STATES', city: 'EFFINGHAM' },
  { bic: 'BYLOU44XXXX', name: 'FIRST MERCHANTS BANK', country: 'UNITED STATES', city: 'MUNCIE' },
  { bic: 'HORZUS44XXX', name: 'HORIZON BANK', country: 'UNITED STATES', city: 'MICHIGAN CITY' },
  { bic: 'LAKEUS44XXX', name: 'LAKELAND FINANCIAL CORP (LAKE CITY BANK)', country: 'UNITED STATES', city: 'WARSAW' },
  { bic: 'GERMUS44XXX', name: 'GERMANTOWN TRUST & SAVINGS BANK', country: 'UNITED STATES', city: 'BREESE' },
  { bic: 'MAINST44XXX', name: 'MAINSTREET BANK', country: 'UNITED STATES', city: 'FAIRFAX' },
  { bic: 'BLUEUS33XXX', name: 'BLUE RIDGE BANK, N.A.', country: 'UNITED STATES', city: 'RICHMOND' },
  { bic: 'CAROUS44XXX', name: 'CAROLINA TRUST BANK', country: 'UNITED STATES', city: 'LINCOLNTON' },
  { bic: 'SOUTUS44XXX', name: 'SOUTHERN FIRST BANK', country: 'UNITED STATES', city: 'GREENVILLE' },

  // ==================== UNITED KINGDOM (Building Societies & Specialist Banks) ====================
  { bic: 'NWBSGB21XXX', name: 'NATIONWIDE BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'SWINDON' },
  { bic: 'COVNGB21XXX', name: 'COVENTRY BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'COVENTRY' },
  { bic: 'YKBSGB21XXX', name: 'YORKSHIRE BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'BRADFORD' },
  { bic: 'SKBSGB21XXX', name: 'SKIPTON BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'SKIPTON' },
  { bic: 'LEBSGB21XXX', name: 'LEEDS BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'LEEDS' },
  { bic: 'PRBSGB21XXX', name: 'PRINCIPALITY BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'CARDIFF' },
  { bic: 'NCBSGB21XXX', name: 'NEWCASTLE BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'NEWCASTLE' },
  { bic: 'NOBSGB21XXX', name: 'NOTTINGHAM BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'NOTTINGHAM' },
  { bic: 'CMBSGB21XXX', name: 'CAMBRIDGE BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'CAMBRIDGE' },
  { bic: 'FNBSGB21XXX', name: 'FURNESS BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'BARROW-IN-FURNESS' },
  { bic: 'SAFFGB21XXX', name: 'SAFFRON BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'SAFFRON WALDEN' },
  { bic: 'NEWBGB21XXX', name: 'NEWBURY BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'NEWBURY' },
  { bic: 'MNBSGB21XXX', name: 'MONMOUTHSHIRE BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'NEWPORT' },
  { bic: 'SCBSGB21XXX', name: 'SCOTTISH BUILDING SOCIETY', country: 'UNITED KINGDOM', city: 'EDINBURGH' },
  { bic: 'CHASGB2LMAN', name: 'JPMORGAN CHASE BANK MANCHESTER', country: 'UNITED KINGDOM', city: 'MANCHESTER' },
  { bic: 'BARCGB22LEE', name: 'BARCLAYS BANK PLC LEEDS', country: 'UNITED KINGDOM', city: 'LEEDS' },
  { bic: 'MIDLGB22BIR', name: 'HSBC BANK PLC BIRMINGHAM COMMERCIAL', country: 'UNITED KINGDOM', city: 'BIRMINGHAM' },
  { bic: 'LOYDGB21BRI', name: 'LLOYDS BANK PLC BRISTOL', country: 'UNITED KINGDOM', city: 'BRISTOL' },
  { bic: 'NWBKGB2LLIV', name: 'NATWEST BANK PLC LIVERPOOL', country: 'UNITED KINGDOM', city: 'LIVERPOOL' },
  { bic: 'RBOSGB2LABZ', name: 'THE ROYAL BANK OF SCOTLAND ABERDEEN', country: 'UNITED KINGDOM', city: 'ABERDEEN' },
  { bic: 'SCBLGB2LGLA', name: 'STANDARD CHARTERED BANK GLASGOW', country: 'UNITED KINGDOM', city: 'GLASGOW' },
  { bic: 'STALGB22XXX', name: 'STARLING BANK LIMITED', country: 'UNITED KINGDOM', city: 'LONDON' },
  { bic: 'MONZGB2XXXX', name: 'MONZO BANK LIMITED', country: 'UNITED KINGDOM', city: 'LONDON' },
  { bic: 'OAKNGB21XXX', name: 'OAKNORTH BANK PLC', country: 'UNITED KINGDOM', city: 'LONDON' },
  { bic: 'SHAWGB21XXX', name: 'SHAWBROOK BANK LIMITED', country: 'UNITED KINGDOM', city: 'BRENTWOOD' },
  { bic: 'ALDRGB21XXX', name: 'ALDERMORE BANK PLC', country: 'UNITED KINGDOM', city: 'READING' },
  { bic: 'PARAGB21XXX', name: 'PARAGON BANK PLC', country: 'UNITED KINGDOM', city: 'SOLIHULL' },
  { bic: 'ONEPGB21XXX', name: 'ONE SAVINGS BANK PLC (OSB GROUP)', country: 'UNITED KINGDOM', city: 'CHATHAM' },
  { bic: 'CHAHGB21XXX', name: 'CHARTER COURT FINANCIAL SERVICES', country: 'UNITED KINGDOM', city: 'WOLVERHAMPTON' },
  { bic: 'ALRGBB21XXX', name: 'AL RAYAN BANK PLC', country: 'UNITED KINGDOM', city: 'BIRMINGHAM' },

  // ==================== GERMANY (Sparkassen, Landesbanken & Genossenschaftsbanken) ====================
  { bic: 'BONSDE33XXX', name: 'SPARKASSE BONN (SPARKASSE KOELNBONN)', country: 'GERMANY', city: 'BONN' },
  { bic: 'STGADE66XXX', name: 'BW-BANK (BADEN-WUERTTEMBERGISCHE BANK)', country: 'GERMANY', city: 'STUTTGART' },
  { bic: 'MAISDE55XXX', name: 'MAINZER VOLKSBANK EG', country: 'GERMANY', city: 'MAINZ' },
  { bic: 'SPMGDE33XXX', name: 'STADTSPARKASSE MOENCHENGLADBACH', country: 'GERMANY', city: 'MONCHENGLADBACH' },
  { bic: 'SPAGDE77XXX', name: 'STADTSPARKASSE AUGSBURG', country: 'GERMANY', city: 'AUGSBURG' },
  { bic: 'SPWIES33XXX', name: 'NASSAUISCHE SPARKASSE WIESBADEN', country: 'GERMANY', city: 'WIESBADEN' },
  { bic: 'SPBSDE22XXX', name: 'BRAUNSCHWEIGISCHE LANDESSPARKASSE', country: 'GERMANY', city: 'BRAUNSCHWEIG' },
  { bic: 'SPCHDE88XXX', name: 'SPARKASSE CHEMNITZ', country: 'GERMANY', city: 'CHEMNITZ' },
  { bic: 'SPKIDE22XXX', name: 'FOERDE SPARKASSE KIEL', country: 'GERMANY', city: 'KIEL' },
  { bic: 'SPHADE88XXX', name: 'SAALESPARKASSE HALLE', country: 'GERMANY', city: 'HALLE' },
  { bic: 'SPMADE88XXX', name: 'STADTSPARKASSE MAGDEBURG', country: 'GERMANY', city: 'MAGDEBURG' },
  { bic: 'SPFRDE66XXX', name: 'SPARKASSE FREIBURG-NOERDLICHER BREISGAU', country: 'GERMANY', city: 'FREIBURG' },
  { bic: 'SPKRDE33XXX', name: 'SPARKASSE KREFELD', country: 'GERMANY', city: 'KREFELD' },
  { bic: 'SPMZDE55XXX', name: 'SPARKASSE MAINZ', country: 'GERMANY', city: 'MAINZ' },
  { bic: 'SPHLDE22XXX', name: 'SPARKASSE ZU LUEBECK AG', country: 'GERMANY', city: 'LUBECK' },
  { bic: 'SPERDE88XXX', name: 'SPARKASSE MITTELTHUERINGEN ERFURT', country: 'GERMANY', city: 'ERFURT' },
  { bic: 'SPRODE22XXX', name: 'OSTSEESPARKASSE ROSTOCK', country: 'GERMANY', city: 'ROSTOCK' },
  { bic: 'SPKSDE55XXX', name: 'KASSELER SPARKASSE', country: 'GERMANY', city: 'KASSEL' },
  { bic: 'SPHGDE33XXX', name: 'SPARKASSE AN VOLME UND RUHR HAGEN', country: 'GERMANY', city: 'HAGEN' },
  { bic: 'SPPMDE88XXX', name: 'MITTELBRANDENBURGISCHE SPARKASSE IN POTSDAM', country: 'GERMANY', city: 'POTSDAM' },
  { bic: 'SPSBDE55XXX', name: 'SPARKASSE SAARBRUECKEN', country: 'GERMANY', city: 'SAARBRUCKEN' },
  { bic: 'SPOLDE22XXX', name: 'LANDESSPARKASSE ZU OLDENBURG', country: 'GERMANY', city: 'OLDENBURG' },
  { bic: 'SPOSDE22XXX', name: 'SPARKASSE OSNABRUECK', country: 'GERMANY', city: 'OSNABRUCK' },
  { bic: 'SPLEDE33XXX', name: 'SPARKASSE LEVERKUSEN', country: 'GERMANY', city: 'LEVERKUSEN' },
  { bic: 'SPHDDE66XXX', name: 'SPARKASSE HEIDELBERG', country: 'GERMANY', city: 'HEIDELBERG' },
  { bic: 'SPSGDE33XXX', name: 'STADTSPARKASSE SOLINGEN', country: 'GERMANY', city: 'SOLINGEN' },
  { bic: 'SPDSDE55XXX', name: 'SPARKASSE DARMSTADT', country: 'GERMANY', city: 'DARMSTADT' },
  { bic: 'SPRGDE77XXX', name: 'SPARKASSE REGENSBURG', country: 'GERMANY', city: 'REGENSBURG' },
  { bic: 'SPPBDE33XXX', name: 'SPARKASSE PADERBORN-DETMOLD-HOEXTER', country: 'GERMANY', city: 'PADERBORN' },
  { bic: 'SPINDE77XXX', name: 'SPARKASSE INGOLSTADT EICHSTAETT', country: 'GERMANY', city: 'INGOLSTADT' },
  { bic: 'SPOFDE55XXX', name: 'STADTSPARKASSE OFFENBACH AM MAIN', country: 'GERMANY', city: 'OFFENBACH' },
  { bic: 'SPWZDE77XXX', name: 'SPARKASSE MAINFRANKEN WUERZBURG', country: 'GERMANY', city: 'WURZBURG' },
  { bic: 'SPULDE66XXX', name: 'SPARKASSE ULM', country: 'GERMANY', city: 'ULM' },
  { bic: 'SPHNDE66XXX', name: 'KREISSPARKASSE HEILBRONN', country: 'GERMANY', city: 'HEILBRONN' },
  { bic: 'SPPFDE66XXX', name: 'SPARKASSE PFORZHEIM CALW', country: 'GERMANY', city: 'PFORZHEIM' },
  { bic: 'SPWOBE22XXX', name: 'VOLKSBANK BRAWO EG WOLFSBURG', country: 'GERMANY', city: 'WOLFSBURG' },
  { bic: 'SPGTDE22XXX', name: 'SPARKASSE GOETTINGEN', country: 'GERMANY', city: 'GOTTINGEN' },
  { bic: 'SPKLDE55XXX', name: 'STADTSPARKASSE KAISERSLAUTERN', country: 'GERMANY', city: 'KAISERSLAUTERN' },
  { bic: 'SPSNDE88XXX', name: 'SPARKASSE MECKLENBURG-SCHWERIN', country: 'GERMANY', city: 'SCHWERIN' },
  { bic: 'SPLUDE66XXX', name: 'KREISSPARKASSE LUDWIGSBURG', country: 'GERMANY', city: 'LUDWIGSBURG' },
  { bic: 'SPESDE66XXX', name: 'KREISSPARKASSE ESSLINGEN-NUERTINGEN', country: 'GERMANY', city: 'ESSLINGEN' },
  { bic: 'GENODEDBMUN', name: 'DZ BANK AG MUENCHEN', country: 'GERMANY', city: 'MUNICH' },
  { bic: 'GENODEDBHAM', name: 'DZ BANK AG HAMBURG', country: 'GERMANY', city: 'HAMBURG' },
  { bic: 'GENODEDBDUS', name: 'DZ BANK AG DUESSELDORF', country: 'GERMANY', city: 'DUSSELDORF' },
  { bic: 'GENODEDBBER', name: 'DZ BANK AG BERLIN', country: 'GERMANY', city: 'BERLIN' },
  { bic: 'GENODEDBSTU', name: 'DZ BANK AG STUTTGART', country: 'GERMANY', city: 'STUTTGART' },
  { bic: 'GENODEDBHAN', name: 'DZ BANK AG HANNOVER', country: 'GERMANY', city: 'HANNOVER' },
  { bic: 'VBMUCDEMMXX', name: 'MUENCHNER BANK EG', country: 'GERMANY', city: 'MUNICH' },
  { bic: 'BEVODEDEEXX', name: 'BERLINER VOLKSBANK EG', country: 'GERMANY', city: 'BERLIN' },
  { bic: 'FFVBDEFFXXX', name: 'FRANKFURTER VOLKSBANK RHEIN/MAIN EG', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'HAMVDEHHXXX', name: 'HAMBURGER VOLKSBANK EG', country: 'GERMANY', city: 'HAMBURG' },
  { bic: 'VOBKDE33XXX', name: 'VOLKSBANK KOELN BONN EG', country: 'GERMANY', city: 'COLOGNE' },
  { bic: 'VBSTDE66XXX', name: 'VOLKSBANK STUTTGART EG', country: 'GERMANY', city: 'STUTTGART' },
  { bic: 'VBDUDE33XXX', name: 'VOLKSBANK DUESSELDORF NEUSS EG', country: 'GERMANY', city: 'DUSSELDORF' },
  { bic: 'VBNUDE77XXX', name: 'VR BANK METROPOLREGION NUERNBERG EG', country: 'GERMANY', city: 'NUREMBERG' },
  { bic: 'VBHNDE2HXXX', name: 'HANNOVERSCHE VOLKSBANK EG', country: 'GERMANY', city: 'HANNOVER' },
  { bic: 'VBBRDE22XXX', name: 'BREMER VOLKSBANK EG', country: 'GERMANY', city: 'BREMEN' },
  { bic: 'VBMUDE33XXX', name: 'VEREINIGTE VOLKSBANK MUENSTER EG', country: 'GERMANY', city: 'MUNSTER' },
  { bic: 'VBDRDE88XXX', name: 'DRESDNER VOLKSBANK RAIFFEISENBANK EG', country: 'GERMANY', city: 'DRESDEN' },
  { bic: 'VBLEDE8LXXX', name: 'LEIPZIGER VOLKSBANK EG', country: 'GERMANY', city: 'LEIPZIG' },
  { bic: 'VBKADE66XXX', name: 'VOLKSBANK KARLSRUHE BADEN-BADEN EG', country: 'GERMANY', city: 'KARLSRUHE' },
  { bic: 'VBAADE33XXX', name: 'AACHENER BANK EG', country: 'GERMANY', city: 'AACHEN' },
  { bic: 'VBFRDE66XXX', name: 'VOLKSBANK FREIBURG EG', country: 'GERMANY', city: 'FREIBURG' },
  { bic: 'VBUGDE77XXX', name: 'VR BANK AUGSBURG-OSTALLGAEU EG', country: 'GERMANY', city: 'AUGSBURG' },
  { bic: 'VBLUDE66XXX', name: 'VR-BANK LUDWIGSBURG EG', country: 'GERMANY', city: 'LUDWIGSBURG' },
  { bic: 'VBESDE66XXX', name: 'VOLKSBANK MITTLERER NECKAR EG ESSLINGEN', country: 'GERMANY', city: 'ESSLINGEN' },
  { bic: 'VBMGDE33XXX', name: 'VOLKSBANK MOENCHENGLADBACH EG', country: 'GERMANY', city: 'MONCHENGLADBACH' },
  { bic: 'VBBIDE33XXX', name: 'VOLKSBANK BIELEFELD-GUETERSLOH EG', country: 'GERMANY', city: 'BIELEFELD' },
  { bic: 'VBWIWIESXXX', name: 'WIESBADENER VOLKSBANK EG', country: 'GERMANY', city: 'WIESBADEN' },
  { bic: 'VBULDE66XXX', name: 'VOLKSBANK ULM-BIBERACH EG', country: 'GERMANY', city: 'ULM' },
  { bic: 'VBOFDE55XXX', name: 'VOLKSBANK OFFENBACH EG', country: 'GERMANY', city: 'OFFENBACH' },
  { bic: 'VBHDDE66XXX', name: 'VOLKSBANK KURPFALZ EG HEIDELBERG', country: 'GERMANY', city: 'HEIDELBERG' },
  { bic: 'VBHNDE66XXX', name: 'VOLKSBANK HEILBRONN EG', country: 'GERMANY', city: 'HEILBRONN' },
  { bic: 'VBPFDE66XXX', name: 'VOLKSBANK PUR EG PFORZHEIM', country: 'GERMANY', city: 'PFORZHEIM' },
  { bic: 'VBWZDE77XXX', name: 'VR-BANK WUERZBURG EG', country: 'GERMANY', city: 'WURZBURG' },
  { bic: 'VBRGDE77XXX', name: 'VOLKSBANK RAIFFEISENBANK REGENSBURG EG', country: 'GERMANY', city: 'REGENSBURG' },
  { bic: 'VBINDE77XXX', name: 'VOLKSBANK RAIFFEISENBANK BAYERN MITTE EG', country: 'GERMANY', city: 'INGOLSTADT' },
  { bic: 'VBLUDE55XXX', name: 'VR BANK RHEIN-NECKAR EG LUDWIGSHAFEN', country: 'GERMANY', city: 'LUDWIGSHAFEN' },
  { bic: 'VBPBDE33XXX', name: 'VERBUNDVOLKSBANK OWL EG PADERBORN', country: 'GERMANY', city: 'PADERBORN' },
  { bic: 'VBOSDE22XXX', name: 'VOLKSBANK OSNABRUECK EG', country: 'GERMANY', city: 'OSNABRUCK' },
  { bic: 'VBOLDE22XXX', name: 'VOLKSBANK OLDENBURG EG', country: 'GERMANY', city: 'OLDENBURG' },
  { bic: 'VBPTDE88XXX', name: 'VOLKSBANK BRB-POTSDAM EG', country: 'GERMANY', city: 'POTSDAM' },
  { bic: 'VBSAAR55XXX', name: 'VOLKSBANK SAARBRUECKEN EG', country: 'GERMANY', city: 'SAARBRUCKEN' },

  // ==================== FRANCE (Crédit Agricole Regional, BPCE Regional, CIC Regional) ====================
  { bic: 'AGRIFRPP888', name: 'CREDIT AGRICOLE D AQUITAINE', country: 'FRANCE', city: 'BORDEAUX' },
  { bic: 'AGRIFRPP889', name: 'CREDIT AGRICOLE DE NORMANDIE', country: 'FRANCE', city: 'CAEN' },
  { bic: 'AGRIFRPP890', name: 'CREDIT AGRICOLE CENTRE-EST', country: 'FRANCE', city: 'LYON' },
  { bic: 'AGRIFRPP891', name: 'CREDIT AGRICOLE NORD DE FRANCE', country: 'FRANCE', city: 'LILLE' },
  { bic: 'AGRIFRPP892', name: 'CREDIT AGRICOLE ATLANTIQUE VENDEE', country: 'FRANCE', city: 'NANTES' },
  { bic: 'AGRIFRPP893', name: 'CREDIT AGRICOLE TOULOUSE 31', country: 'FRANCE', city: 'TOULOUSE' },
  { bic: 'AGRIFRPP894', name: 'CREDIT AGRICOLE LOIRE HAUTE-LOIRE', country: 'FRANCE', city: 'SAINT-ETIENNE' },
  { bic: 'AGRIFRPP895', name: 'CREDIT AGRICOLE DU MORBIHAN', country: 'FRANCE', city: 'VANNES' },
  { bic: 'AGRIFRPP896', name: 'CREDIT AGRICOLE DU FINISTERE', country: 'FRANCE', city: 'QUIMPER' },
  { bic: 'AGRIFRPP897', name: 'CREDIT AGRICOLE ILLE-ET-VILAINE', country: 'FRANCE', city: 'RENNES' },
  { bic: 'AGRIFRPP898', name: 'CREDIT AGRICOLE DE LORRAINE', country: 'FRANCE', city: 'METZ' },
  { bic: 'AGRIFRPP899', name: 'CREDIT AGRICOLE ALSACE VOSGES', country: 'FRANCE', city: 'STRASBOURG' },
  { bic: 'AGRIFRPP900', name: 'CREDIT AGRICOLE CHAMPAGNE-BOURGOGNE', country: 'FRANCE', city: 'DIJON' },
  { bic: 'AGRIFRPP901', name: 'CREDIT AGRICOLE DE FRANCHE-COMTE', country: 'FRANCE', city: 'BESANCON' },
  { bic: 'AGRIFRPP902', name: 'CREDIT AGRICOLE DES SAVOIE', country: 'FRANCE', city: 'ANNECY' },
  { bic: 'AGRIFRPP903', name: 'CREDIT AGRICOLE PYRENEES GASCOGNE', country: 'FRANCE', city: 'PAU' },
  { bic: 'AGRIFRPP904', name: 'CREDIT AGRICOLE DU LANGUEDOC', country: 'FRANCE', city: 'MONTPELLIER' },
  { bic: 'AGRIFRPP905', name: 'CREDIT AGRICOLE SUD RHONE ALPES', country: 'FRANCE', city: 'GRENOBLE' },
  { bic: 'AGRIFRPP906', name: 'CREDIT AGRICOLE CENTRE FRANCE', country: 'FRANCE', city: 'CLERMONT-FERRAND' },
  { bic: 'AGRIFRPP907', name: 'CREDIT AGRICOLE CHARENTE-PERIGORD', country: 'FRANCE', city: 'ANGOULEME' },
  { bic: 'AGRIFRPP908', name: 'CREDIT AGRICOLE CHARENTE-MARITIME DEUX-SEVRES', country: 'FRANCE', city: 'LA ROCHELLE' },
  { bic: 'AGRIFRPP909', name: 'CREDIT AGRICOLE TOURAINE POITOU', country: 'FRANCE', city: 'POITIERS' },
  { bic: 'AGRIFRPP910', name: 'CREDIT AGRICOLE VAL DE FRANCE', country: 'FRANCE', city: 'CHARTRES' },
  { bic: 'AGRIFRPP911', name: 'CREDIT AGRICOLE CENTRE LOIRE', country: 'FRANCE', city: 'BOURGES' },
  { bic: 'AGRIFRPP912', name: 'CREDIT AGRICOLE ANJOU MAINE', country: 'FRANCE', city: 'ANGERS' },
  { bic: 'AGRIFRPP913', name: 'CREDIT AGRICOLE DE NORMANDIE-SEINE', country: 'FRANCE', city: 'ROUEN' },
  { bic: 'AGRIFRPP914', name: 'CREDIT AGRICOLE BRIE PICARDIE', country: 'FRANCE', city: 'AMIENS' },
  { bic: 'AGRIFRPP915', name: 'CREDIT AGRICOLE DU NORD EST', country: 'FRANCE', city: 'REIMS' },
  { bic: 'AGRIFRPP916', name: 'CREDIT AGRICOLE NORD MIDI-PYRENEES', country: 'FRANCE', city: 'ALBI' },
  { bic: 'AGRIFRPP917', name: 'CREDIT AGRICOLE DE GUADELOUPE', country: 'FRANCE', city: 'POINTE-A-PITRE' },
  { bic: 'AGRIFRPP918', name: 'CREDIT AGRICOLE DE LA MARTINIQUE ET GUYANE', country: 'FRANCE', city: 'LE LAMENTIN' },
  { bic: 'AGRIFRPP919', name: 'CREDIT AGRICOLE DE LA REUNION', country: 'FRANCE', city: 'SAINT-DENIS' },
  { bic: 'AGRIFRPP920', name: 'CREDIT AGRICOLE DE CORSE', country: 'FRANCE', city: 'AJACCIO' },
  { bic: 'BPOPFR22XXX', name: 'BANQUE POPULAIRE GRAND OUEST', country: 'FRANCE', city: 'RENNES' },
  { bic: 'BPOPFR23XXX', name: 'BANQUE POPULAIRE DU SUD', country: 'FRANCE', city: 'PERPIGNAN' },
  { bic: 'BPOPFR24XXX', name: 'BANQUE POPULAIRE OCCITANE', country: 'FRANCE', city: 'BALMA' },
  { bic: 'BPOPFR25XXX', name: 'BANQUE POPULAIRE AUVERGNE RHONE ALPES', country: 'FRANCE', city: 'LYON' },
  { bic: 'BPOPFR26XXX', name: 'BANQUE POPULAIRE MEDITERRANEE', country: 'FRANCE', city: 'MARSEILLE' },
  { bic: 'BPOPFR27XXX', name: 'BANQUE POPULAIRE BOURGOGNE FRANCHE-COMTE', country: 'FRANCE', city: 'DIJON' },
  { bic: 'BPOPFR28XXX', name: 'BANQUE POPULAIRE ALSACE LORRAINE CHAMPAGNE', country: 'FRANCE', city: 'STRASBOURG' },
  { bic: 'BPOPFR29XXX', name: 'BANQUE POPULAIRE DU NORD', country: 'FRANCE', city: 'MARCQ-EN-BAROEUL' },
  { bic: 'BPOPFR30XXX', name: 'BANQUE POPULAIRE VAL DE FRANCE', country: 'FRANCE', city: 'SAINT-QUENTIN-EN-YVELINES' },
  { bic: 'BPOPFR31XXX', name: 'BANQUE POPULAIRE AQUITAINE CENTRE ATLANTIQUE', country: 'FRANCE', city: 'BORDEAUX' },
  { bic: 'CEPAFR21XXX', name: 'CAISSE D EPARGNE BRETAGNE PAYS DE LOIRE', country: 'FRANCE', city: 'NANTES' },
  { bic: 'CEPAFR22XXX', name: 'CAISSE D EPARGNE CEPAC (MARSEILLE)', country: 'FRANCE', city: 'MARSEILLE' },
  { bic: 'CEPAFR23XXX', name: 'CAISSE D EPARGNE GRAND EST EUROPE', country: 'FRANCE', city: 'STRASBOURG' },
  { bic: 'CEPAFR24XXX', name: 'CAISSE D EPARGNE HAUTS DE FRANCE', country: 'FRANCE', city: 'LILLE' },
  { bic: 'CEPAFR25XXX', name: 'CAISSE D EPARGNE LOIRE-CENTRE', country: 'FRANCE', city: 'ORLEANS' },
  { bic: 'CEPAFR26XXX', name: 'CAISSE D EPARGNE DE MIDI-PYRENEES', country: 'FRANCE', city: 'TOULOUSE' },
  { bic: 'CEPAFR27XXX', name: 'CAISSE D EPARGNE DE NORMANDIE', country: 'FRANCE', city: 'ROUEN' },
  { bic: 'CEPAFR28XXX', name: 'CAISSE D EPARGNE LANGUEDOC-ROUSSILLON', country: 'FRANCE', city: 'MONTPELLIER' },
  { bic: 'CEPAFR29XXX', name: 'CAISSE D EPARGNE AQUITAINE POITOU-CHARENTES', country: 'FRANCE', city: 'BORDEAUX' },
  { bic: 'CEPAFR30XXX', name: 'CAISSE D EPARGNE BOURGOGNE FRANCHE-COMTE', country: 'FRANCE', city: 'DIJON' },
  { bic: 'CEPAFR31XXX', name: 'CAISSE D EPARGNE D AUVERGNE ET DU LIMOUSIN', country: 'FRANCE', city: 'CLERMONT-FERRAND' },
  { bic: 'CEPAFR32XXX', name: 'CAISSE D EPARGNE COTE D AZUR', country: 'FRANCE', city: 'NICE' },

  // ==================== ITALY (Regional Banking Groups) ====================
  { bic: 'CRBZIT2BXXX', name: 'CASSA DI RISPARMIO DI BOLZANO S.P.A. (SPARKASSE)', country: 'ITALY', city: 'BOLZANO' },
  { bic: 'CRATIT22XXX', name: 'CASSA DI RISPARMIO DI ASTI S.P.A. (BANCA CR ASTI)', country: 'ITALY', city: 'ASTI' },
  { bic: 'CRRAIT22XXX', name: 'CASSA DI RISPARMIO DI RAVENNA S.P.A.', country: 'ITALY', city: 'RAVENNA' },
  { bic: 'CRVOIT22XXX', name: 'CASSA DI RISPARMIO DI VOLTERRA S.P.A.', country: 'ITALY', city: 'VOLTERRA' },
  { bic: 'CRFEIT22XXX', name: 'CASSA DI RISPARMIO DI FERMO S.P.A.', country: 'ITALY', city: 'FERMO' },
  { bic: 'CRBIIT22XXX', name: 'CASSA DI RISPARMIO DI BIELLA E VERCELLI S.P.A.', country: 'ITALY', city: 'BIELLA' },
  { bic: 'CRFOIT22XXX', name: 'CASSA DI RISPARMIO DI FOSSANO S.P.A.', country: 'ITALY', city: 'FOSSANO' },
  { bic: 'CRSAIT22XXX', name: 'CASSA DI RISPARMIO DI SAVIGLIANO S.P.A.', country: 'ITALY', city: 'SAVIGLIANO' },
  { bic: 'CRCENT22XXX', name: 'CASSA DI RISPARMIO DI CENTO S.P.A.', country: 'ITALY', city: 'CENTO' },
  { bic: 'CRORIT22XXX', name: 'CASSA DI RISPARMIO DI ORVIETO S.P.A.', country: 'ITALY', city: 'ORVIETO' },
  { bic: 'BPPBIT22XXX', name: 'BANCA POPOLARE DI PUGLIA E BASILICATA S.C.P.A.', country: 'ITALY', city: 'ALTAMURA' },
  { bic: 'BPLAIT22XXX', name: 'BANCA POPOLARE DEL LAZIO S.C.P.A.', country: 'ITALY', city: 'VELLETRI' },
  { bic: 'FUCIT22XXXX', name: 'BANCA DEL FUCINO S.P.A.', country: 'ITALY', city: 'ROME' },
  { bic: 'PASPIT22XXX', name: 'BANCA PASSADORE & C. S.P.A.', country: 'ITALY', city: 'GENOA' },
  { bic: 'BPFDIT22XXX', name: 'BANCA POPOLARE DI FONDI S.C.P.A.', country: 'ITALY', city: 'FONDI' },
  { bic: 'BPCIIT22XXX', name: 'BANCA DI PIACENZA S.C.P.A.', country: 'ITALY', city: 'PIACENZA' },
  { bic: 'CAMBIT22XXX', name: 'BANCA CAMBIANO 1884 S.P.A.', country: 'ITALY', city: 'FLORENCE' },
  { bic: 'CESSIT22XXX', name: 'BANCA DI CREDITO COOPERATIVO DI BRESCIA', country: 'ITALY', city: 'BRESCIA' },
  { bic: 'ROMAIT22XXX', name: 'BANCA DI CREDITO COOPERATIVO DI ROMA S.C.', country: 'ITALY', city: 'ROME' },
  { bic: 'MILRAIT22XXX', name: 'BANCA POPOLARE DI MILANO S.P.A. (BANCO BPM)', country: 'ITALY', city: 'MILAN' },
  { bic: 'VEROIT22XXX', name: 'BANCO POPOLARE DI VERONA S.P.A.', country: 'ITALY', city: 'VERONA' },
  { bic: 'NOVRAIT22XXX', name: 'BANCA POPOLARE DI NOVARA S.P.A.', country: 'ITALY', city: 'NOVARA' },
  { bic: 'LODIIT22XXX', name: 'BANCA POPOLARE DI LODI S.P.A.', country: 'ITALY', city: 'LODI' },
  { bic: 'BERGIT22XXX', name: 'BANCA POPOLARE DI BERGAMO S.P.A.', country: 'ITALY', city: 'BERGAMO' },
  { bic: 'ANCOIT22XXX', name: 'BANCA POPOLARE DI ANCONA S.P.A.', country: 'ITALY', city: 'ANCONA' },

  // ==================== SPAIN (Cajas Rurales & Specialist Entities) ====================
  { bic: 'CRNAES2PXXX', name: 'CAJA RURAL DE NAVARRA, S. COOP. DE CREDITO', country: 'SPAIN', city: 'PAMPLONA' },
  { bic: 'CRGRES21XXX', name: 'CAJA RURAL DE GRANADA, S.C.C.', country: 'SPAIN', city: 'GRANADA' },
  { bic: 'CRSRES21XXX', name: 'CAJA RURAL DEL SUR, S. COOP. DE CREDITO', country: 'SPAIN', city: 'SEVILLE' },
  { bic: 'CRJAES21XXX', name: 'CAJA RURAL DE JAEN, BARCELONA Y MADRID, S.C.C.', country: 'SPAIN', city: 'JAEN' },
  { bic: 'CRTEES21XXX', name: 'CAJA RURAL DE TERUEL, S.C.C.', country: 'SPAIN', city: 'TERUEL' },
  { bic: 'CRZAES21XXX', name: 'CAJA RURAL DE ZAMORA, C.C.', country: 'SPAIN', city: 'ZAMORA' },
  { bic: 'CRCEES21XXX', name: 'CAJA RURAL CENTRAL, S.C.C.', country: 'SPAIN', city: 'ORIHUELA' },
  { bic: 'CRALES21XXX', name: 'CAJAMAR CAJA RURAL, SOCIEDAD COOPERATIVA DE CREDITO', country: 'SPAIN', city: 'ALMERIA' },
  { bic: 'CRTOES21XXX', name: 'EUROCAJA RURAL, SOCIEDAD COOPERATIVA DE CREDITO', country: 'SPAIN', city: 'TOLEDO' },
  { bic: 'CRGIES21XXX', name: 'CAJA RURAL DE GIJON, C.C.', country: 'SPAIN', city: 'GIJON' },
  { bic: 'CRSOES21XXX', name: 'CAJA RURAL DE SORIA, S.C.C.', country: 'SPAIN', city: 'SORIA' },
  { bic: 'CRUBES21XXX', name: 'CAJA RURAL DE EXTREMADURA, S.C.C.', country: 'SPAIN', city: 'BADAJOZ' },
  { bic: 'CRARES21XXX', name: 'CAJA RURAL DE ARAGON, S.C.C. (BANTIERRA)', country: 'SPAIN', city: 'ZARAGOZA' },
  { bic: 'LABAES21XXX', name: 'LABORAL KUTXA (CAJA LABORAL POPULAR COOP DE CREDITO)', country: 'SPAIN', city: 'MONDRAGON' },
  { bic: 'RCOPES21XXX', name: 'BANCO COOPERATIVO ESPANOL, S.A.', country: 'SPAIN', city: 'MADRID' },

  // ==================== JAPAN (Tier-1 and Tier-2 Regional Banks) ====================
  { bic: 'ASHKJPJTXXX', name: 'THE ASHIKAGA BANK, LTD.', country: 'JAPAN', city: 'UTSUNOMIYA' },
  { bic: 'TOCHJPJTXXX', name: 'THE TOCHIGI BANK, LTD.', country: 'JAPAN', city: 'UTSUNOMIYA' },
  { bic: 'TSUKJPJTXXX', name: 'THE TSUKUBA BANK, LTD.', country: 'JAPAN', city: 'TSUKUBA' },
  { bic: 'MUSAJPJTXXX', name: 'THE MUSASHINO BANK, LTD.', country: 'JAPAN', city: 'SAITAMA' },
  { bic: 'CHIKJPJTXXX', name: 'THE CHIBA KOGYO BANK, LTD.', country: 'JAPAN', city: 'CHIBA' },
  { bic: 'STARJPJTXXX', name: 'THE TOKYO STAR BANK, LIMITED', country: 'JAPAN', city: 'TOKYO' },
  { bic: 'KANAJPJTXXX', name: 'THE KANAGAWA BANK, LTD.', country: 'JAPAN', city: 'YOKOHAMA' },
  { bic: 'YAMAJP22XXX', name: 'THE YAMANASHI CHUO BANK, LTD.', country: 'JAPAN', city: 'KOFU' },
  { bic: 'NAGAJPJTXXX', name: 'THE NAGANO BANK, LTD.', country: 'JAPAN', city: 'MATSUMOTO' },
  { bic: 'FUKIJPJTXXX', name: 'THE FUKUI BANK, LTD.', country: 'JAPAN', city: 'FUKUI' },
  { bic: 'FUKUJP22XXX', name: 'THE FUKUHO BANK, LTD.', country: 'JAPAN', city: 'FUKUI' },
  { bic: 'SHIGJPJTXXX', name: 'THE SHIGA BANK, LTD.', country: 'JAPAN', city: 'OTSU' },
  { bic: 'NANTJPJTXXX', name: 'THE NANTO BANK, LTD.', country: 'JAPAN', city: 'NARA' },
  { bic: 'KIYOJPJTXXX', name: 'THE KIYO BANK, LTD.', country: 'JAPAN', city: 'WAKAYAMA' },
  { bic: 'TAJMJPJTXXX', name: 'THE TAJIMA BANK, LTD.', country: 'JAPAN', city: 'TOYOOKA' },
  { bic: 'TOTTJPJTXXX', name: 'THE TOTTORI BANK, LTD.', country: 'JAPAN', city: 'TOTTORI' },
  { bic: 'SHIMJPJTXXX', name: 'THE SHIMANE BANK, LTD.', country: 'JAPAN', city: 'MATSUE' },
  { bic: 'TOMAJPJTXXX', name: 'THE TOMATO BANK, LTD.', country: 'JAPAN', city: 'OKAYAMA' },
  { bic: 'MOMIJPJTXXX', name: 'THE MOMIJI BANK, LTD.', country: 'JAPAN', city: 'HIROSHIMA' },
  { bic: 'YAMGJPJTXXX', name: 'THE YAMAGUCHI BANK, LTD.', country: 'JAPAN', city: 'SHIMONOSEKI' },
  { bic: 'TOKUJPJTXXX', name: 'THE TOKUSHIMA TAISHO BANK, LTD.', country: 'JAPAN', city: 'TOKUSHIMA' },
  { bic: 'KAGAJPJTXXX', name: 'THE KAGAWA BANK, LTD.', country: 'JAPAN', city: 'TAKAMATSU' },
  { bic: 'EHIMJPJTXXX', name: 'THE EHIME BANK, LTD.', country: 'JAPAN', city: 'MATSUYAMA' },
  { bic: 'KOCHJPJTXXX', name: 'THE KOCHI BANK, LTD.', country: 'JAPAN', city: 'KOCHI' },
  { bic: 'FKCHJPJTXXX', name: 'THE FUKUOKA CHUO BANK, LTD.', country: 'JAPAN', city: 'FUKUOKA' },
  { bic: 'SAGAKJPJTXX', name: 'THE SAGA KYOEI BANK, LTD.', country: 'JAPAN', city: 'SAGA' },
  { bic: 'NAGSJPJTXXX', name: 'THE NAGASAKI BANK, LTD.', country: 'JAPAN', city: 'NAGASAKI' },
  { bic: 'KUMAJPJTXXX', name: 'THE KUMAMOTO BANK, LTD.', country: 'JAPAN', city: 'KUMAMOTO' },
  { bic: 'TYOBJPJTXXX', name: 'THE MIYAZAKI TAIYO BANK, LTD.', country: 'JAPAN', city: 'MIYAZAKI' },
  { bic: 'MINMJPJTXXX', name: 'THE MINAMI NIPPON BANK, LTD.', country: 'JAPAN', city: 'KAGOSHIMA' },
  { bic: 'OKKYJPJTXXX', name: 'THE OKINAWA KAIKYO BANK, LTD.', country: 'JAPAN', city: 'NAHA' },

  // ==================== GLOBAL FINANCIAL CENTRES & TRADE CLEARING HUBS ====================
  // SWIFT hubs in Zurich, Geneva, Frankfurt, London, Singapore, Hong Kong, New York, Tokyo, Sydney
  { bic: 'CHASDEFFXXX', name: 'J.P. MORGAN AG (FRANKFURT SEPA CLEARING)', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'CITIDEFFXXX', name: 'CITIGROUP GLOBAL MARKETS EUROPE AG', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'GSCODEFFXXX', name: 'GOLDMAN SACHS BANK EUROPE SE', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'MSNYDEFFXXX', name: 'MORGAN STANLEY EUROPE SE', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'BOFADEFFXXX', name: 'BOFA SECURITIES EUROPE SA (FRANKFURT)', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'BNPADEFFXXX', name: 'BNP PARIBAS S.A. NIEDERLASSUNG DEUTSCHLAND', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'SOGEDEFFXXX', name: 'SOCIETE GENERALE S.A. FRANKFURT', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'UBSWDEFFXXX', name: 'UBS EUROPE SE', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'CRESDEFFXXX', name: 'CREDIT SUISSE (DEUTSCHLAND) AG', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'BARCDEFFXXX', name: 'BARCLAYS BANK IRELAND PLC FRANKFURT', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'HSBCDEFFXXX', name: 'HSBC TRINKAUS & BURKHARDT GMBH', country: 'GERMANY', city: 'DUSSELDORF' },
  { bic: 'SEBADEFFXXX', name: 'SEB AG (SKANDINAVISKA ENSKILDA BANKEN FRANKFURT)', country: 'GERMANY', city: 'FRANKFURT AM MAIN' },
  { bic: 'MBLXLU22XXX', name: 'BANQUE MARCHANDE DE LUXEMBOURG', country: 'LUXEMBOURG', city: 'LUXEMBOURG' },
  { bic: 'EIBKLULLXXX', name: 'EUROPEAN INVESTMENT BANK (EIB)', country: 'LUXEMBOURG', city: 'LUXEMBOURG' },
  { bic: 'ESMMLULLXXX', name: 'EUROPEAN STABILITY MECHANISM (ESM)', country: 'LUXEMBOURG', city: 'LUXEMBOURG' },
  { bic: 'CEDELULLXXX', name: 'CLEARSTREAM BANKING S.A.', country: 'LUXEMBOURG', city: 'LUXEMBOURG' },
  { bic: 'EBCOBEBBXXX', name: 'EUROCLEAR BANK SA/NV', country: 'BELGIUM', city: 'BRUSSELS' },
  { bic: 'SWFTBEB1XXX', name: 'S.W.I.F.T. SC (SWIFT HEADQUARTERS LA HULPE)', country: 'BELGIUM', city: 'LA HULPE' },
  { bic: 'BISPCH22XXX', name: 'BANK FOR INTERNATIONAL SETTLEMENTS (BIS)', country: 'SWITZERLAND', city: 'BASEL' },
  { bic: 'ARABJOAMXXX', name: 'ARAB BANK PLC', country: 'JORDAN', city: 'AMMAN' },
  { bic: 'HBLBPKKAXXX', name: 'HABIB BANK LIMITED (HBL)', country: 'PAKISTAN', city: 'KARACHI' },
  { bic: 'MCBPKKAXXXX', name: 'MCB BANK LIMITED', country: 'PAKISTAN', city: 'LAHORE' },
  { bic: 'NBPAPKKXXXX', name: 'NATIONAL BANK OF PAKISTAN', country: 'PAKISTAN', city: 'KARACHI' },
  { bic: 'UBLPPKKAXXX', name: 'UNITED BANK LIMITED (UBL)', country: 'PAKISTAN', city: 'KARACHI' },
  { bic: 'BBLBBDDHXXX', name: 'BRAC BANK LIMITED', country: 'BANGLADESH', city: 'DHAKA' },
  { bic: 'EBLBBDDHXXX', name: 'EASTERN BANK LIMITED', country: 'BANGLADESH', city: 'DHAKA' },
  { bic: 'SONABDDAXXX', name: 'SONALI BANK LIMITED', country: 'BANGLADESH', city: 'DHAKA' },
  { bic: 'BOCELKKLXXX', name: 'BANK OF CEYLON', country: 'SRI LANKA', city: 'COLOMBO' },
  { bic: 'COMBCEKLXXX', name: 'COMMERCIAL BANK OF CEYLON PLC', country: 'SRI LANKA', city: 'COLOMBO' },
  { bic: 'HNBCLKKLXXX', name: 'HATTON NATIONAL BANK PLC', country: 'SRI LANKA', city: 'COLOMBO' }
];

fs.writeFileSync(path.join(process.cwd(), 'scripts/banks_network.js'), `export const networkBanks = ${JSON.stringify(networkBanks, null, 2)};\n`);
console.log(`Network & Regional banks compiled: ${networkBanks.length}`);
